### ISSUE TITLE
Could not find or access '/opt/software/nomad_1.1.0_linux_amd64.zip

### ISSUE THREAD

**Issue by manbobo2002** [lework/Ansible-roles#8]
```
TASK [ansible-nomad : install | Copy nomad file to agent.] ***********************************************************************************************************fatal: [xxxx]: FAILED! => {"changed": false, "msg": "Could not find or access '/opt/software/nomad_1.1.0_linux_amd64.zip' on the Ansible Controller.\nIf you 
are using a module and expect the file to exist on the remote, see the remote_src option"}
```

solution:
```
- name: install | Copy nomad file to agent.
  unarchive:
    src: "{{ nomad_file_path }}"
    dest: "{{ nomad_bin_path }}"
    creates: "{{ nomad_bin_path }}/nomad"
    remote_src: yes
```
add remote_src: yes
